// Code generated by MockGen. DO NOT EDIT.
// Source: ../types/conn.go
//
// Generated by this command:
//
//	mockgen -source=../types/conn.go -destination=lazy_acquire_mocks_test.go -package=conns
//

// Package conns is a generated GoMock package.
package conns

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	xoptional "github.com/Deimvis/go-ext/go1.25/xoptional"
	types "github.com/Deimvis-go/xpg/pg/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockConn is a mock of Conn interface.
type MockConn struct {
	ctrl     *gomock.Controller
	recorder *MockConnMockRecorder
	isgomock struct{}
}

// MockConnMockRecorder is the mock recorder for MockConn.
type MockConnMockRecorder struct {
	mock *MockConn
}

// NewMockConn creates a new mock instance.
func NewMockConn(ctrl *gomock.Controller) *MockConn {
	mock := &MockConn{ctrl: ctrl}
	mock.recorder = &MockConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConn) EXPECT() *MockConnMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockConn) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockConnMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockConn)(nil).Begin), ctx)
}

// BeginTx mocks base method.
func (m *MockConn) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockConnMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockConn)(nil).BeginTx), ctx, txOptions)
}

// CopyFrom mocks base method.
func (m *MockConn) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockConnMockRecorder) CopyFrom(ctx, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockConn)(nil).CopyFrom), ctx, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockConnMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockConn)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockConn) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockConnMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockConn)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockConnMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockConn)(nil).QueryRow), varargs...)
}

// SendBatch mocks base method.
func (m *MockConn) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockConnMockRecorder) SendBatch(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockConn)(nil).SendBatch), ctx, b)
}

// MockStandaloneConn is a mock of StandaloneConn interface.
type MockStandaloneConn struct {
	ctrl     *gomock.Controller
	recorder *MockStandaloneConnMockRecorder
	isgomock struct{}
}

// MockStandaloneConnMockRecorder is the mock recorder for MockStandaloneConn.
type MockStandaloneConnMockRecorder struct {
	mock *MockStandaloneConn
}

// NewMockStandaloneConn creates a new mock instance.
func NewMockStandaloneConn(ctrl *gomock.Controller) *MockStandaloneConn {
	mock := &MockStandaloneConn{ctrl: ctrl}
	mock.recorder = &MockStandaloneConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStandaloneConn) EXPECT() *MockStandaloneConnMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockStandaloneConn) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockStandaloneConnMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockStandaloneConn)(nil).Begin), ctx)
}

// BeginTx mocks base method.
func (m *MockStandaloneConn) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockStandaloneConnMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockStandaloneConn)(nil).BeginTx), ctx, txOptions)
}

// Close mocks base method.
func (m *MockStandaloneConn) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStandaloneConnMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStandaloneConn)(nil).Close), ctx)
}

// CopyFrom mocks base method.
func (m *MockStandaloneConn) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockStandaloneConnMockRecorder) CopyFrom(ctx, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockStandaloneConn)(nil).CopyFrom), ctx, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockStandaloneConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockStandaloneConnMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockStandaloneConn)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockStandaloneConn) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockStandaloneConnMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockStandaloneConn)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockStandaloneConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockStandaloneConnMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockStandaloneConn)(nil).QueryRow), varargs...)
}

// SendBatch mocks base method.
func (m *MockStandaloneConn) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockStandaloneConnMockRecorder) SendBatch(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockStandaloneConn)(nil).SendBatch), ctx, b)
}

// MockPoolConn is a mock of PoolConn interface.
type MockPoolConn struct {
	ctrl     *gomock.Controller
	recorder *MockPoolConnMockRecorder
	isgomock struct{}
}

// MockPoolConnMockRecorder is the mock recorder for MockPoolConn.
type MockPoolConnMockRecorder struct {
	mock *MockPoolConn
}

// NewMockPoolConn creates a new mock instance.
func NewMockPoolConn(ctrl *gomock.Controller) *MockPoolConn {
	mock := &MockPoolConn{ctrl: ctrl}
	mock.recorder = &MockPoolConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolConn) EXPECT() *MockPoolConnMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockPoolConn) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockPoolConnMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockPoolConn)(nil).Begin), ctx)
}

// BeginTx mocks base method.
func (m *MockPoolConn) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockPoolConnMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockPoolConn)(nil).BeginTx), ctx, txOptions)
}

// CopyFrom mocks base method.
func (m *MockPoolConn) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockPoolConnMockRecorder) CopyFrom(ctx, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockPoolConn)(nil).CopyFrom), ctx, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockPoolConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockPoolConnMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPoolConn)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockPoolConn) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPoolConnMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPoolConn)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockPoolConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockPoolConnMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockPoolConn)(nil).QueryRow), varargs...)
}

// Release mocks base method.
func (m *MockPoolConn) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockPoolConnMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockPoolConn)(nil).Release))
}

// SendBatch mocks base method.
func (m *MockPoolConn) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockPoolConnMockRecorder) SendBatch(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockPoolConn)(nil).SendBatch), ctx, b)
}

// MockConnReflect is a mock of ConnReflect interface.
type MockConnReflect struct {
	ctrl     *gomock.Controller
	recorder *MockConnReflectMockRecorder
	isgomock struct{}
}

// MockConnReflectMockRecorder is the mock recorder for MockConnReflect.
type MockConnReflectMockRecorder struct {
	mock *MockConnReflect
}

// NewMockConnReflect creates a new mock instance.
func NewMockConnReflect(ctrl *gomock.Controller) *MockConnReflect {
	mock := &MockConnReflect{ctrl: ctrl}
	mock.recorder = &MockConnReflectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnReflect) EXPECT() *MockConnReflectMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockConnReflect) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockConnReflectMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockConnReflect)(nil).Begin), ctx)
}

// BeginTx mocks base method.
func (m *MockConnReflect) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockConnReflectMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockConnReflect)(nil).BeginTx), ctx, txOptions)
}

// CopyFrom mocks base method.
func (m *MockConnReflect) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockConnReflectMockRecorder) CopyFrom(ctx, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockConnReflect)(nil).CopyFrom), ctx, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockConnReflect) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockConnReflectMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockConnReflect)(nil).Exec), varargs...)
}

// IsLazy mocks base method.
func (m *MockConnReflect) IsLazy() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLazy")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// IsLazy indicates an expected call of IsLazy.
func (mr *MockConnReflectMockRecorder) IsLazy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLazy", reflect.TypeOf((*MockConnReflect)(nil).IsLazy))
}

// IsOneTime mocks base method.
func (m *MockConnReflect) IsOneTime() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOneTime")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// IsOneTime indicates an expected call of IsOneTime.
func (mr *MockConnReflectMockRecorder) IsOneTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOneTime", reflect.TypeOf((*MockConnReflect)(nil).IsOneTime))
}

// Mode mocks base method.
func (m *MockConnReflect) Mode() xoptional.T[types.ConnMode] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mode")
	ret0, _ := ret[0].(xoptional.T[types.ConnMode])
	return ret0
}

// Mode indicates an expected call of Mode.
func (mr *MockConnReflectMockRecorder) Mode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mode", reflect.TypeOf((*MockConnReflect)(nil).Mode))
}

// OwnershipTaken mocks base method.
func (m *MockConnReflect) OwnershipTaken() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnershipTaken")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// OwnershipTaken indicates an expected call of OwnershipTaken.
func (mr *MockConnReflectMockRecorder) OwnershipTaken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnershipTaken", reflect.TypeOf((*MockConnReflect)(nil).OwnershipTaken))
}

// Query mocks base method.
func (m *MockConnReflect) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockConnReflectMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockConnReflect)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockConnReflect) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockConnReflectMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockConnReflect)(nil).QueryRow), varargs...)
}

// SendBatch mocks base method.
func (m *MockConnReflect) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockConnReflectMockRecorder) SendBatch(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockConnReflect)(nil).SendBatch), ctx, b)
}

// TakeOwnership mocks base method.
func (m *MockConnReflect) TakeOwnership() (types.OwnedConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeOwnership")
	ret0, _ := ret[0].(types.OwnedConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeOwnership indicates an expected call of TakeOwnership.
func (mr *MockConnReflectMockRecorder) TakeOwnership() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeOwnership", reflect.TypeOf((*MockConnReflect)(nil).TakeOwnership))
}

// MockLazyConn is a mock of LazyConn interface.
type MockLazyConn struct {
	ctrl     *gomock.Controller
	recorder *MockLazyConnMockRecorder
	isgomock struct{}
}

// MockLazyConnMockRecorder is the mock recorder for MockLazyConn.
type MockLazyConnMockRecorder struct {
	mock *MockLazyConn
}

// NewMockLazyConn creates a new mock instance.
func NewMockLazyConn(ctrl *gomock.Controller) *MockLazyConn {
	mock := &MockLazyConn{ctrl: ctrl}
	mock.recorder = &MockLazyConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLazyConn) EXPECT() *MockLazyConnMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockLazyConn) Acquire() types.LazyConnAcquireError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire")
	ret0, _ := ret[0].(types.LazyConnAcquireError)
	return ret0
}

// Acquire indicates an expected call of Acquire.
func (mr *MockLazyConnMockRecorder) Acquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockLazyConn)(nil).Acquire))
}

// AcquireArgs mocks base method.
func (m *MockLazyConn) AcquireArgs() (context.Context, types.ConnMode, []types.ConnAcquireOption) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireArgs")
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(types.ConnMode)
	ret2, _ := ret[2].([]types.ConnAcquireOption)
	return ret0, ret1, ret2
}

// AcquireArgs indicates an expected call of AcquireArgs.
func (mr *MockLazyConnMockRecorder) AcquireArgs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireArgs", reflect.TypeOf((*MockLazyConn)(nil).AcquireArgs))
}

// Acquired mocks base method.
func (m *MockLazyConn) Acquired() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquired")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Acquired indicates an expected call of Acquired.
func (mr *MockLazyConnMockRecorder) Acquired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquired", reflect.TypeOf((*MockLazyConn)(nil).Acquired))
}

// Begin mocks base method.
func (m *MockLazyConn) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockLazyConnMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockLazyConn)(nil).Begin), ctx)
}

// BeginTx mocks base method.
func (m *MockLazyConn) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockLazyConnMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockLazyConn)(nil).BeginTx), ctx, txOptions)
}

// CopyFrom mocks base method.
func (m *MockLazyConn) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockLazyConnMockRecorder) CopyFrom(ctx, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockLazyConn)(nil).CopyFrom), ctx, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockLazyConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockLazyConnMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockLazyConn)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockLazyConn) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockLazyConnMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockLazyConn)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockLazyConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockLazyConnMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockLazyConn)(nil).QueryRow), varargs...)
}

// SendBatch mocks base method.
func (m *MockLazyConn) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockLazyConnMockRecorder) SendBatch(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockLazyConn)(nil).SendBatch), ctx, b)
}

// MockConnMeta is a mock of ConnMeta interface.
type MockConnMeta struct {
	ctrl     *gomock.Controller
	recorder *MockConnMetaMockRecorder
	isgomock struct{}
}

// MockConnMetaMockRecorder is the mock recorder for MockConnMeta.
type MockConnMetaMockRecorder struct {
	mock *MockConnMeta
}

// NewMockConnMeta creates a new mock instance.
func NewMockConnMeta(ctrl *gomock.Controller) *MockConnMeta {
	mock := &MockConnMeta{ctrl: ctrl}
	mock.recorder = &MockConnMetaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnMeta) EXPECT() *MockConnMetaMockRecorder {
	return m.recorder
}

// IsLazy mocks base method.
func (m *MockConnMeta) IsLazy() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLazy")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// IsLazy indicates an expected call of IsLazy.
func (mr *MockConnMetaMockRecorder) IsLazy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLazy", reflect.TypeOf((*MockConnMeta)(nil).IsLazy))
}

// IsOneTime mocks base method.
func (m *MockConnMeta) IsOneTime() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOneTime")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// IsOneTime indicates an expected call of IsOneTime.
func (mr *MockConnMetaMockRecorder) IsOneTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOneTime", reflect.TypeOf((*MockConnMeta)(nil).IsOneTime))
}

// Mode mocks base method.
func (m *MockConnMeta) Mode() xoptional.T[types.ConnMode] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mode")
	ret0, _ := ret[0].(xoptional.T[types.ConnMode])
	return ret0
}

// Mode indicates an expected call of Mode.
func (mr *MockConnMetaMockRecorder) Mode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mode", reflect.TypeOf((*MockConnMeta)(nil).Mode))
}

// OwnershipTaken mocks base method.
func (m *MockConnMeta) OwnershipTaken() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnershipTaken")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// OwnershipTaken indicates an expected call of OwnershipTaken.
func (mr *MockConnMetaMockRecorder) OwnershipTaken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnershipTaken", reflect.TypeOf((*MockConnMeta)(nil).OwnershipTaken))
}

// MockMutableConnMeta is a mock of MutableConnMeta interface.
type MockMutableConnMeta struct {
	ctrl     *gomock.Controller
	recorder *MockMutableConnMetaMockRecorder
	isgomock struct{}
}

// MockMutableConnMetaMockRecorder is the mock recorder for MockMutableConnMeta.
type MockMutableConnMetaMockRecorder struct {
	mock *MockMutableConnMeta
}

// NewMockMutableConnMeta creates a new mock instance.
func NewMockMutableConnMeta(ctrl *gomock.Controller) *MockMutableConnMeta {
	mock := &MockMutableConnMeta{ctrl: ctrl}
	mock.recorder = &MockMutableConnMetaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutableConnMeta) EXPECT() *MockMutableConnMetaMockRecorder {
	return m.recorder
}

// IsLazy mocks base method.
func (m *MockMutableConnMeta) IsLazy() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLazy")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// IsLazy indicates an expected call of IsLazy.
func (mr *MockMutableConnMetaMockRecorder) IsLazy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLazy", reflect.TypeOf((*MockMutableConnMeta)(nil).IsLazy))
}

// IsOneTime mocks base method.
func (m *MockMutableConnMeta) IsOneTime() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOneTime")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// IsOneTime indicates an expected call of IsOneTime.
func (mr *MockMutableConnMetaMockRecorder) IsOneTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOneTime", reflect.TypeOf((*MockMutableConnMeta)(nil).IsOneTime))
}

// Mode mocks base method.
func (m *MockMutableConnMeta) Mode() xoptional.T[types.ConnMode] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mode")
	ret0, _ := ret[0].(xoptional.T[types.ConnMode])
	return ret0
}

// Mode indicates an expected call of Mode.
func (mr *MockMutableConnMetaMockRecorder) Mode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mode", reflect.TypeOf((*MockMutableConnMeta)(nil).Mode))
}

// OwnershipTaken mocks base method.
func (m *MockMutableConnMeta) OwnershipTaken() xoptional.T[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnershipTaken")
	ret0, _ := ret[0].(xoptional.T[bool])
	return ret0
}

// OwnershipTaken indicates an expected call of OwnershipTaken.
func (mr *MockMutableConnMetaMockRecorder) OwnershipTaken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnershipTaken", reflect.TypeOf((*MockMutableConnMeta)(nil).OwnershipTaken))
}

// TakeOwnership mocks base method.
func (m *MockMutableConnMeta) TakeOwnership() (types.OwnedConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeOwnership")
	ret0, _ := ret[0].(types.OwnedConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeOwnership indicates an expected call of TakeOwnership.
func (mr *MockMutableConnMetaMockRecorder) TakeOwnership() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeOwnership", reflect.TypeOf((*MockMutableConnMeta)(nil).TakeOwnership))
}

// MockOwnedConn is a mock of OwnedConn interface.
type MockOwnedConn struct {
	ctrl     *gomock.Controller
	recorder *MockOwnedConnMockRecorder
	isgomock struct{}
}

// MockOwnedConnMockRecorder is the mock recorder for MockOwnedConn.
type MockOwnedConnMockRecorder struct {
	mock *MockOwnedConn
}

// NewMockOwnedConn creates a new mock instance.
func NewMockOwnedConn(ctrl *gomock.Controller) *MockOwnedConn {
	mock := &MockOwnedConn{ctrl: ctrl}
	mock.recorder = &MockOwnedConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnedConn) EXPECT() *MockOwnedConnMockRecorder {
	return m.recorder
}

// Free mocks base method.
func (m *MockOwnedConn) Free(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Free", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Free indicates an expected call of Free.
func (mr *MockOwnedConnMockRecorder) Free(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Free", reflect.TypeOf((*MockOwnedConn)(nil).Free), arg0)
}

// MockLazyConnAcquireError is a mock of LazyConnAcquireError interface.
type MockLazyConnAcquireError struct {
	ctrl     *gomock.Controller
	recorder *MockLazyConnAcquireErrorMockRecorder
	isgomock struct{}
}

// MockLazyConnAcquireErrorMockRecorder is the mock recorder for MockLazyConnAcquireError.
type MockLazyConnAcquireErrorMockRecorder struct {
	mock *MockLazyConnAcquireError
}

// NewMockLazyConnAcquireError creates a new mock instance.
func NewMockLazyConnAcquireError(ctrl *gomock.Controller) *MockLazyConnAcquireError {
	mock := &MockLazyConnAcquireError{ctrl: ctrl}
	mock.recorder = &MockLazyConnAcquireErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLazyConnAcquireError) EXPECT() *MockLazyConnAcquireErrorMockRecorder {
	return m.recorder
}

// AcquireArgs mocks base method.
func (m *MockLazyConnAcquireError) AcquireArgs() (context.Context, types.ConnMode, []types.ConnAcquireOption) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireArgs")
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(types.ConnMode)
	ret2, _ := ret[2].([]types.ConnAcquireOption)
	return ret0, ret1, ret2
}

// AcquireArgs indicates an expected call of AcquireArgs.
func (mr *MockLazyConnAcquireErrorMockRecorder) AcquireArgs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireArgs", reflect.TypeOf((*MockLazyConnAcquireError)(nil).AcquireArgs))
}

// Error mocks base method.
func (m *MockLazyConnAcquireError) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockLazyConnAcquireErrorMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLazyConnAcquireError)(nil).Error))
}
