// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pgfw

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	mock "github.com/stretchr/testify/mock"
	pgconn0 "github.com/Deimvis-go/xpg/pg/pgconn"
)

// NewMockConn creates a new instance of MockConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConn {
	mock := &MockConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConn is an autogenerated mock type for the Conn type
type MockConn struct {
	mock.Mock
}

type MockConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConn) EXPECT() *MockConn_Expecter {
	return &MockConn_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockConn
func (_mock *MockConn) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockConn_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConn_Expecter) Begin(ctx interface{}) *MockConn_Begin_Call {
	return &MockConn_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockConn_Begin_Call) Run(run func(ctx context.Context)) *MockConn_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConn_Begin_Call) Return(tx pgx.Tx, err error) *MockConn_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockConn_Begin_Call) RunAndReturn(run func(ctx context.Context) (pgx.Tx, error)) *MockConn_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function for the type MockConn
func (_mock *MockConn) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockConn_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *MockConn_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *MockConn_BeginTx_Call {
	return &MockConn_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *MockConn_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *MockConn_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConn_BeginTx_Call) Return(tx pgx.Tx, err error) *MockConn_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockConn_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *MockConn_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFrom provides a mock function for the type MockConn
func (_mock *MockConn) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	ret := _mock.Called(ctx, tableName, columnNames, rowSrc)

	if len(ret) == 0 {
		panic("no return value specified for CopyFrom")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) (int64, error)); ok {
		return returnFunc(ctx, tableName, columnNames, rowSrc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) int64); ok {
		r0 = returnFunc(ctx, tableName, columnNames, rowSrc)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Identifier, []string, pgx.CopyFromSource) error); ok {
		r1 = returnFunc(ctx, tableName, columnNames, rowSrc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_CopyFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFrom'
type MockConn_CopyFrom_Call struct {
	*mock.Call
}

// CopyFrom is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName pgx.Identifier
//   - columnNames []string
//   - rowSrc pgx.CopyFromSource
func (_e *MockConn_Expecter) CopyFrom(ctx interface{}, tableName interface{}, columnNames interface{}, rowSrc interface{}) *MockConn_CopyFrom_Call {
	return &MockConn_CopyFrom_Call{Call: _e.mock.On("CopyFrom", ctx, tableName, columnNames, rowSrc)}
}

func (_c *MockConn_CopyFrom_Call) Run(run func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource)) *MockConn_CopyFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Identifier
		if args[1] != nil {
			arg1 = args[1].(pgx.Identifier)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 pgx.CopyFromSource
		if args[3] != nil {
			arg3 = args[3].(pgx.CopyFromSource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConn_CopyFrom_Call) Return(n int64, err error) *MockConn_CopyFrom_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockConn_CopyFrom_Call) RunAndReturn(run func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error)) *MockConn_CopyFrom_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockConn
func (_mock *MockConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockConn_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockConn_Expecter) Exec(ctx interface{}, sql interface{}, args ...interface{}) *MockConn_Exec_Call {
	return &MockConn_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockConn_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockConn_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockConn_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockConn_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockConn_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)) *MockConn_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockConn
func (_mock *MockConn) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConn_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockConn_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockConn_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *MockConn_Query_Call {
	return &MockConn_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockConn_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockConn_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockConn_Query_Call) Return(rows pgx.Rows, err error) *MockConn_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockConn_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)) *MockConn_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockConn
func (_mock *MockConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// MockConn_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockConn_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockConn_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *MockConn_QueryRow_Call {
	return &MockConn_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockConn_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockConn_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockConn_QueryRow_Call) Return(row pgx.Row) *MockConn_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockConn_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) pgx.Row) *MockConn_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// SendBatch provides a mock function for the type MockConn
func (_mock *MockConn) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 pgx.BatchResults
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Batch) pgx.BatchResults); ok {
		r0 = returnFunc(ctx, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.BatchResults)
		}
	}
	return r0
}

// MockConn_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type MockConn_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - b *pgx.Batch
func (_e *MockConn_Expecter) SendBatch(ctx interface{}, b interface{}) *MockConn_SendBatch_Call {
	return &MockConn_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, b)}
}

func (_c *MockConn_SendBatch_Call) Run(run func(ctx context.Context, b *pgx.Batch)) *MockConn_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Batch
		if args[1] != nil {
			arg1 = args[1].(*pgx.Batch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConn_SendBatch_Call) Return(batchResults pgx.BatchResults) *MockConn_SendBatch_Call {
	_c.Call.Return(batchResults)
	return _c
}

func (_c *MockConn_SendBatch_Call) RunAndReturn(run func(ctx context.Context, b *pgx.Batch) pgx.BatchResults) *MockConn_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnOwnership creates a new instance of MockConnOwnership. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnOwnership(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnOwnership {
	mock := &MockConnOwnership{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnOwnership is an autogenerated mock type for the ConnOwnership type
type MockConnOwnership struct {
	mock.Mock
}

type MockConnOwnership_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnOwnership) EXPECT() *MockConnOwnership_Expecter {
	return &MockConnOwnership_Expecter{mock: &_m.Mock}
}

// MustTake provides a mock function for the type MockConnOwnership
func (_mock *MockConnOwnership) MustTake() pgconn0.OwnedConn {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MustTake")
	}

	var r0 pgconn0.OwnedConn
	if returnFunc, ok := ret.Get(0).(func() pgconn0.OwnedConn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgconn0.OwnedConn)
		}
	}
	return r0
}

// MockConnOwnership_MustTake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustTake'
type MockConnOwnership_MustTake_Call struct {
	*mock.Call
}

// MustTake is a helper method to define mock.On call
func (_e *MockConnOwnership_Expecter) MustTake() *MockConnOwnership_MustTake_Call {
	return &MockConnOwnership_MustTake_Call{Call: _e.mock.On("MustTake")}
}

func (_c *MockConnOwnership_MustTake_Call) Run(run func()) *MockConnOwnership_MustTake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnOwnership_MustTake_Call) Return(ownedConn pgconn0.OwnedConn) *MockConnOwnership_MustTake_Call {
	_c.Call.Return(ownedConn)
	return _c
}

func (_c *MockConnOwnership_MustTake_Call) RunAndReturn(run func() pgconn0.OwnedConn) *MockConnOwnership_MustTake_Call {
	_c.Call.Return(run)
	return _c
}

// Take provides a mock function for the type MockConnOwnership
func (_mock *MockConnOwnership) Take() (pgconn0.OwnedConn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Take")
	}

	var r0 pgconn0.OwnedConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (pgconn0.OwnedConn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() pgconn0.OwnedConn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgconn0.OwnedConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnOwnership_Take_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Take'
type MockConnOwnership_Take_Call struct {
	*mock.Call
}

// Take is a helper method to define mock.On call
func (_e *MockConnOwnership_Expecter) Take() *MockConnOwnership_Take_Call {
	return &MockConnOwnership_Take_Call{Call: _e.mock.On("Take")}
}

func (_c *MockConnOwnership_Take_Call) Run(run func()) *MockConnOwnership_Take_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnOwnership_Take_Call) Return(ownedConn pgconn0.OwnedConn, err error) *MockConnOwnership_Take_Call {
	_c.Call.Return(ownedConn, err)
	return _c
}

func (_c *MockConnOwnership_Take_Call) RunAndReturn(run func() (pgconn0.OwnedConn, error)) *MockConnOwnership_Take_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPoolManager creates a new instance of MockPoolManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoolManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPoolManager {
	mock := &MockPoolManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPoolManager is an autogenerated mock type for the PoolManager type
type MockPoolManager struct {
	mock.Mock
}

type MockPoolManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPoolManager) EXPECT() *MockPoolManager_Expecter {
	return &MockPoolManager_Expecter{mock: &_m.Mock}
}

// GetPool provides a mock function for the type MockPoolManager
func (_mock *MockPoolManager) GetPool(connMode pgconn0.Mode) *pgxpool.Pool {
	ret := _mock.Called(connMode)

	if len(ret) == 0 {
		panic("no return value specified for GetPool")
	}

	var r0 *pgxpool.Pool
	if returnFunc, ok := ret.Get(0).(func(pgconn0.Mode) *pgxpool.Pool); ok {
		r0 = returnFunc(connMode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Pool)
		}
	}
	return r0
}

// MockPoolManager_GetPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPool'
type MockPoolManager_GetPool_Call struct {
	*mock.Call
}

// GetPool is a helper method to define mock.On call
//   - connMode pgconn0.Mode
func (_e *MockPoolManager_Expecter) GetPool(connMode interface{}) *MockPoolManager_GetPool_Call {
	return &MockPoolManager_GetPool_Call{Call: _e.mock.On("GetPool", connMode)}
}

func (_c *MockPoolManager_GetPool_Call) Run(run func(connMode pgconn0.Mode)) *MockPoolManager_GetPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgconn0.Mode
		if args[0] != nil {
			arg0 = args[0].(pgconn0.Mode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPoolManager_GetPool_Call) Return(pool *pgxpool.Pool) *MockPoolManager_GetPool_Call {
	_c.Call.Return(pool)
	return _c
}

func (_c *MockPoolManager_GetPool_Call) RunAndReturn(run func(connMode pgconn0.Mode) *pgxpool.Pool) *MockPoolManager_GetPool_Call {
	_c.Call.Return(run)
	return _c
}
